
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\hp\Desktop\osss\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x600")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    800.0,
    600.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    111.0,
    146.0,
    anchor="nw",
    text="Every tool you need to work with PDF in one place",
    fill="#1E1E1E",
    font=("AbrilFatface Regular", 24 * -1)
)

canvas.create_rectangle(
    428.0,
    439.0,
    753.0,
    498.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    428.0,
    367.0,
    753.0,
    426.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    428.0,
    212.0,
    753.0,
    271.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    428.0,
    292.0,
    753.0,
    351.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    428.0,
    439.0,
    753.0,
    498.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    428.0,
    367.0,
    753.0,
    426.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    428.0,
    212.0,
    753.0,
    271.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    436.0,
    217.0,
    484.572021484375,
    267.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    435.0,
    295.0,
    485.0,
    346.9245910644531,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    800.0,
    140.0,
    fill="#A61313",
    outline="")

canvas.create_text(
    47.0,
    24.0,
    anchor="nw",
    text="OS Converter",
    fill="#FFFFFF",
    font=("Limelight Regular", 96 * -1)
)

canvas.create_rectangle(
    41.0,
    439.0,
    366.0,
    498.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    160.0,
    442.0,
    anchor="nw",
    text="image to pdf ",
    fill="#160000",
    font=("LondrinaSolid Regular", 24 * -1)
)

canvas.create_rectangle(
    47.70731735229492,
    442.0729064941406,
    99.12820816040039,
    494.41161727905273,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    140.39024353027344,
    474.6458435058594,
    anchor="nw",
    text="convert image to pdf in second",
    fill="#110101",
    font=("LondrinaSolid Regular", 14 * -1)
)

canvas.create_rectangle(
    41.0,
    367.0,
    366.0,
    426.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    160.0,
    370.0,
    anchor="nw",
    text="image to pdf ",
    fill="#160000",
    font=("LondrinaSolid Regular", 24 * -1)
)

canvas.create_rectangle(
    47.70731735229492,
    370.0729064941406,
    99.12820816040039,
    422.41162109375,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    140.39024353027344,
    402.6458435058594,
    anchor="nw",
    text="convert image to pdf in second",
    fill="#110101",
    font=("LondrinaSolid Regular", 14 * -1)
)

canvas.create_rectangle(
    41.0,
    212.0,
    366.0,
    271.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    160.0,
    215.0,
    anchor="nw",
    text="image to pdf ",
    fill="#160000",
    font=("LondrinaSolid Regular", 24 * -1)
)

canvas.create_rectangle(
    47.70731735229492,
    215.07293701171875,
    99.12820816040039,
    267.4116516113281,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    140.39024353027344,
    247.64581298828125,
    anchor="nw",
    text="convert image to pdf in second",
    fill="#110101",
    font=("LondrinaSolid Regular", 14 * -1)
)

canvas.create_rectangle(
    41.0,
    292.0,
    366.0,
    351.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    160.0,
    295.0,
    anchor="nw",
    text="pdf to image ",
    fill="#160000",
    font=("LondrinaSolid Regular", 24 * -1)
)

canvas.create_rectangle(
    48.0,
    296.0,
    98.0,
    346.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    140.39024353027344,
    327.64581298828125,
    anchor="nw",
    text="convert pdf to image in second",
    fill="#110101",
    font=("LondrinaSolid Regular", 14 * -1)
)

canvas.create_rectangle(
    41.0,
    439.0,
    366.0,
    498.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    150.0,
    442.0,
    anchor="nw",
    text="pdf to word",
    fill="#160000",
    font=("LondrinaSolid Regular", 24 * -1)
)

canvas.create_text(
    139.0,
    472.0,
    anchor="nw",
    text="convert pdf to word in second",
    fill="#110101",
    font=("LondrinaSolid Regular", 14 * -1)
)

canvas.create_rectangle(
    50.0,
    443.0,
    97.24770736694336,
    493.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    41.0,
    367.0,
    366.0,
    426.0,
    fill="#000000",
    outline="")

canvas.create_text(
    150.0,
    371.0,
    anchor="nw",
    text="word to pdf",
    fill="#160000",
    font=("LondrinaSolid Regular", 24 * -1)
)

canvas.create_text(
    126.0,
    400.0,
    anchor="nw",
    text="convert your DOC and DOCX to pdf",
    fill="#110101",
    font=("LondrinaSolid Regular", 14 * -1)
)

canvas.create_rectangle(
    48.0,
    371.0,
    99.81818389892578,
    421.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    41.0,
    212.0,
    366.0,
    271.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    160.0,
    215.0,
    anchor="nw",
    text="image to pdf ",
    fill="#160000",
    font=("LondrinaSolid Regular", 24 * -1)
)

canvas.create_rectangle(
    47.70731735229492,
    215.07293701171875,
    99.12820816040039,
    267.4116516113281,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    140.39024353027344,
    247.64581298828125,
    anchor="nw",
    text="convert image to pdf in second",
    fill="#110101",
    font=("LondrinaSolid Regular", 14 * -1)
)

canvas.create_rectangle(
    436.0,
    372.0,
    484.2532653808594,
    422.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    435.0,
    443.0,
    482.5,
    493.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
